formatter: "markdown table"

content: |-
  {{ .Header }}
  {{ .Requirements }}
  {{ .Providers }}
  {{ .Inputs }}
  {{ .Modules }}
  {{ .Resources }}
  {{ .Outputs }}
  {{ .Footer }}

output:
  file: ../../../docs/queues_topics.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->